# -*- coding: utf-8 -*-
"""Flipr.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vF2Olc5U9aQkYhTDk5flJbR6nPGIhEmv
"""

import pandas as pd
import numpy as np

df = pd.read_csv('covid19india.csv')

df.head()

df.columns

"""We only need the following columns:

​“patient id, reported on, age estimate,
gender, state, status” 

Hence we will drop rest of the columns
"""

df.drop(['onsetEstimate', 'city', 'district', 'notes', 'contractedFrom'], inplace = True, axis = 1)

df.head()

df_columns = df.columns.to_list()

df.isnull().sum()

"""We can see that most of null values are in the columns 'ageEstimate' and 'Gender'. The number of null values are also pretty huge so we can't drop these values but in contrast the number of null values in state is 1, we can drop that particular row.

Dropping that particular row
"""

df.dropna(axis = 0, subset = ['state'], inplace = True)

df['gender'].value_counts()

df.isnull().sum()

ratio_of_male_to_female = df['gender'].value_counts().values[0] / df['gender'].value_counts().values[1]
print("Ratio of number of males to female given is", round(ratio_of_male_to_female, 2))

import random
while(df['gender'].isnull().sum() != 0):
    df['gender'].fillna(random.randint(0, 1),inplace = True, limit = 1)

df['gender'].value_counts()

gender = {0 : 'Male', 1 : 'Female', 'male' : 'Male', 'female' : 'Female' }
df['gender'] = df['gender'].map(gender)

df['gender'].value_counts()

df.isnull().sum()

df.shape

test = df.copy()

test.shape

df.shape

to_be_dropped = df['ageEstimate'].isnull()

to_be_dropped.shape

df.dropna(axis = 0, subset = ['ageEstimate'], inplace = True)

df.shape

test.shape

print(type(list(df['ageEstimate'])[0]))

"""As the values for ageEstimate is a string and not integer, we won't be able to take mean, hence we need to convert to integer"""

age = list(df['ageEstimate'])
for i in range(len(age)):
  if age[i] == '28-35': #There is a value of '28-35', which will cause problem while converting to float.
    age[i] = '30'
  age[i] = float(age[i])

age_mean = round(np.mean(age))
age_mean

t = 0

dropped_age = list(to_be_dropped.values)
for i in range(0, len(dropped_age)):
  dropped_age[i] = str(dropped_age[i])
  if dropped_age[i] == 'False':
    dropped_age[i] = age[t]
    t += 1
    
  if dropped_age[i] == 'True':
    dropped_age[i] = age_mean

len(dropped_age)

test.shape

test['ageEstimate'] = pd.Series(dropped_age)

test.dropna(inplace = True)

test.isnull().sum()

test.to_csv('finalcovid19india.csv')
